import LocalizedStrings from 'react-native-localization';
let stringsoflanguages = new LocalizedStrings({
 en:{
   hello:"Hello",
   hey:"Welcome to Mehwar",
   mob:"MOBILE NO.",
   pass:"PASSWORD",
   forg:"Forgot Password",
   sign:"Sign in",
   or:"OR",
   connect:"Connect with Facebook",
   connect2:"Connect with Google",
   new:"New to Mehwar?",
   up:"Sign Up",
   start:"Sign up to get started.",
   name:"FULL NAME",
   exp1:"Abc def",
   email:"EMAIL ADDRESS",
   exp2:"abc@gmail.com",
   mobile:"MOBILE NO.",
   exp3:"+91 9876543213",
   already:"Already have an account?",
   verify:"Verification",
   text:"We texted you a code to verify",
   your:"your phone number",
   not:"I did not receive a code",
   resend:"Resend",
   mehwar:"Mehwar",
   admin:"By Admin",
   time:"2 hours ago",
   experience:"How was your experience today?",
   exe:"Excellent",
   good:"Good",
   avg:"Average",
   sub:"Submit",
   protect:"Protective Measures Against Coronavirus",
   covid:"COVID-19",
   read:"Read More",
   no1:"1125",
   no2:"348",
  add1:"Jan 21, 2020",
  add2:"Protective Measures…",
  add3:"A distance of at least 1 meter is necessary to ensure safety for all",
  latest:"Latest News",
  lat:"A distance of at least 1 meter is necessary to ensure",
  est:"safety for all",
  survey:"All Survey",
  which:"Which one of our new products you love the most?",
  add4:"SAT, JUN 15  7:30 PM",
  add5:"Jazz Night",
  add6:"The Square . San Francisco",
  event:"Latest Events",
  about:"About Us",
   vision:"Our Vision",
   mission:"Our Mission",
   new1:"Lorem Ipsum is simply dummy text of the printing",
   new2:"and typesetting industry. Lorem Ipsum has been",
   new3:"the industry's standard dummy text ever since the",
   new4:"1500s, when an unknown printer took a galley of",
   new5:"type and scrambled it to make a type specimen",
   new6:"book.",
   ent:"Please enter your email id or mobile",
   res:"number to reset your password",
   reset:"Reset Password",
   code:"Reset code was sent to your email/mobile.",
   cret:"Please enter the code and create new password.",
   res2:"reset code",
   newpass:"NEW PASSWORD",
   confirm:"CONFIRM PASSWORD",




 },
 ps:{
   hello:"سلام",
   hey:"مهور ته ښه راغلاست",
   mob:"د موبایل نمبر.",
   pass:"رمز",
   forg:"خپل پټ نوم درڅخه هیر دی",
   sign:"ننوزئ",
   or:"او",
   connect:"له فېسبوک سره وصل شئ",
   connect2:"د ګوګل سره وصل شئ",
   new:"مهروت ته نوی؟",
   up:"ګډون کول",
   start:"د پیل لپاره لاسلیک وکړئ.",
   name:"بشپړ نوم",
   exp1:"د Abc Def",
   email:"بریښنالیک",
   exp2:"abc@gmail.com",
   mobile:"د موبایل نمبر.",
   exp3:"+91 9876543213",
   already:"دمخه یو حساب لرئ؟",
   verify:"تصدیقول",
   text:"موږ تاسو ته د تایید لپاره کوډ درلیږلو",
   your:"ستاسو د تلیفون شمیره",
   not:"ما کوډ نه دی ترلاسه کړی",
   resend:"بیا ولولئ",
   mehwar:"مهور",
   admin:"د ایڈمن لخوا",
   time:"2 ساعته دمخه",
   experience:"نن ورځ ستاسو تجربه څنګه وه؟",
   exe:"عالي",
   good:"ښه",
   avg:"اوسط",
   sub:"وسپارئ",
   protect:"د کورونوایرس پروړاندې محافظتي اقدامات",
   covid:"COVID-19",
   read:"نور یی ولوله",
   no1:"1125",
   no2:"348",
     add1:"21 جنوري ، 2020",
     add2:"محافظتي اقدامات ...",
     add3:"د ټولو لپاره د خوندیتوب تضمین لپاره لږترلږه 1 متره فاصله اړینه ده",
     latest:"تازه ترین خبرونه",
     lat:"د ډاډ ترلاسه کولو لپاره لږترلږه 1 متره فاصله اړینه ده",
     est:"د ټولو لپاره خوندیتوب",
     survey:"ټوله سروې",
     which:"کوم یو زموږ نوی محصولات تاسو سره ډیره مینه لرئ؟",
     add4:"سیټ ، جون 15 7:30 ماښام",
     add5:"جاز شپه",
     add6:"چوکۍ. سن فرانسیسکو",
     event:"وروستۍ پیښې",
     about:"زموږ په اړه",
   vision:"زموږ لید",
   mission:"زموږ ماموریت",
   new1:"لوریم ایپسم د چاپ کولو ساده ب simplyه متن دی",
   new2:"او ټایپسټینګ صنعت. لوریم ایپسوم و",
   new3:"له کله راهیسې د صنعت معیاري جعلي متن",
   new4:"1500s ، کله چې یو ناپیژندل شوی چاپګر د ګالی ګیلاس واخیست",
   new5:"ټایپ وکړئ او د دې لپاره چې دا ډول نمونه جوړه کړئ",
   new6:"کتاب.",
   ent:"مهرباني وکړئ خپل بریښنالیک ID یا موبایل دننه کړئ",
   res:"د خپل رمز بیا تنظیمولو لپاره شمیره",
   reset:"شفر بیا جوړول",
   code:"د ریسیډ کوډ ستاسو بریښنالیک / موبایل ته لیږل شوی و",
   cret:"مهرباني وکړئ کوډ دننه کړئ او نوی رمز مو جوړ کړئ.",
   res2:"کوډ بیا تنظیم کړئ",
   newpass:"نوئ پټ نوم",
   confirm:"پاسورډ تایید کړهتأیید رمز عبور",

 },
 fa: {
   hello:"سلام",
   hey:"به مهوار خوش آمدید",
   mob:"هیچ موبایل.",
   pass: "کلمه عبور",
   forg:"رمز عبور را فراموش کرده اید",
   sign:"ورود",
   or:"یا",
   connect:"با Facebook ارتباط برقرار کنید",
   connect2:"با Google ارتباط برقرار کنید",
   new:"جدید برای Mehwar؟",
   up:"ثبت نام",
   start:"برای شروع ثبت نام کنید.",
   name:"نام و نام خانوادگی",
   exp1:"ABC دف",
   email:"آدرس ایمیل",
   exp2:"abc@gmail.com",
   mobile:"هیچ موبایل.",
   exp3:"+91 9876543213",
   already:"قبلاً حساب دارید؟",
   verify:"تایید",
   text:"ما برای تأیید کد به شما پیامک دادیم",
   your:"شماره تلفن شما",
   not:"من کدی دریافت نکردم",
   resend:"ارسال مجدد",
   mehwar:"مهوار",
   admin:"توسط مدیر",
   time:"2 ساعت پیش",
   experience:"تجربه امروز شما چطور بود؟",
   exe:"عالی",
   good:"خوب",
   avg:"میانگین",
   sub:"ارسال",
   protect:"اقدامات محافظتی در برابر ویروس کرونا",
   covid:"کووید -19",
   read:"ادامه مطلب",
   no1:"یک هزار و صد و بیست و پنج",
   no2:"سیصد و چهل و هشت",
   add1:"21 ژانویه 2020",
   add2:"اقدامات محافظتی",
   add3:"حداقل یک متر فاصله برای اطمینان از ایمنی همه لازم است",
   latest:"آخرین خبرها",
   lat:"برای اطمینان از فاصله حداقل 1 متر لازم است",
   est:"ایمنی برای همه",
   survey:"همه نظرسنجی ها",
   which:"کدام یک از محصولات جدید ما را بیشتر دوست دارید؟",
   add4:"SAT ، 15 ژوئن 7:30 بعد از ظهر",
   add5:"شب جاز",
   add6:"مربع . سانفرانسیسکو",
   event:"آخرین رویدادها",
   about:"درباره ما",
   vision:"دیدگاه ما",
   mission:"ماموریت ما",
   new1:"Lorem Ipsum به سادگی متن ساختگی چاپ است",
   new2:"و صنعت حروفچینی. لورم ایپسوم بوده است",
   new3:"متن ساختگی استاندارد این صنعت از زمان",
   new4:"1500s ، هنگامی که یک چاپگر ناشناخته یک گالری را گرفت",
   new5:"تایپ کنید و آنرا مخلوط کنید تا نمونه ای از نوع آن ساخته شود",
   new6:"کتاب.",
   ent:"لطفاً شناسه ایمیل یا تلفن همراه خود را وارد کنید",
   res:"شماره را برای تنظیم مجدد رمز عبور خود وارد کنید",
   reset:"بازنشانی گذرواژه",
   code:"بازنشانی کد به ایمیل / تلفن همراه شما ارسال شد",
   cret:"لطفاً کد را وارد کرده و گذرواژه جدیدی ایجاد کنید.",
   res2:"تنظیم مجدد کد",
   newpass:"رمز عبور جدید",
   confirm:"تأیید رمز عبور",
 }
});

export default stringsoflanguages;